name: New release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.git-cliff.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header

  build:
    name: Publish files
    runs-on: ubuntu-latest
    needs: generate-changelog
    
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Prepare release assets
      shell: bash
      run: |
        mkdir -p release-${{ env.CURRENT_VERSION }}/{scripts,systemd}
        cp scripts/backup-flow.sh release-${{ env.CURRENT_VERSION }}/scripts/backup-flow.sh
        cp -r systemd/* release-${{ env.CURRENT_VERSION }}/systemd
        tar -czvf backup-flow-${{ env.CURRENT_VERSION }}.tar.gz release-${{ env.CURRENT_VERSION }}/
      env:
        CURRENT_VERSION: ${{ github.ref_name }}
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: backup-flow-${{ github.ref_name }}.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        make_latest: true
        body: "${{ needs.generate-changelog.outputs.release_body }}"
